- hosts: localhost
  become: true
  become_user: root
  tasks:
    # Fix for containerd conflict
    - name: Remove conflicting packages
      apt:
        name: 
          - containerd
          - docker.io
        state: absent
        autoremove: yes

    # Retry Docker installation
    - name: Install Docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes
