---
- hosts: localhost
  become: true  # Run with sudo privileges
  become_user: root
  tasks:
    # Remove any apt locks using wait_for for better reliability
    - name: Wait for apt lock release
      wait_for:
        path: /var/lib/apt/lists/lock
        state: absent
        timeout: 60
      ignore_errors: yes

    - name: Wait for dpkg lock release
      wait_for:
        path: /var/lib/dpkg/lock
        state: absent
        timeout: 60
      ignore_errors: yes

    - name: Wait for dpkg-frontend lock release
      wait_for:
        path: /var/lib/dpkg/lock-frontend
        state: absent
        timeout: 60
      ignore_errors: yes

    # Configure apt sources correctly
    - name: Configure apt repositories
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
        mode: '0644'

    - name: Clean apt cache
      command: apt-get clean

    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: apt_update_result

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: no
      loop:
        - docker.io
        - python3-pip

    # Install docker-compose via pip for reliability
    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user | default('ubuntu') }}"
        groups: docker
        append: yes

