---
- hosts: localhost
  become: true  # Run with sudo privileges
  become_user: root
  tasks:
    # Remove any apt locks
    - name: Ensure no apt lock exists
      file:
        path: /var/lib/apt/lists/lock
        state: absent
      ignore_errors: yes

    - name: Ensure no apt lock exists for dpkg
      file:
        path: /var/lib/dpkg/lock
        state: absent
      ignore_errors: yes

    - name: Ensure no apt lock exists for dpkg-frontend
      file:
        path: /var/lib/dpkg/lock-frontend
        state: absent
      ignore_errors: yes

    - name: Wait for lock release
      command: sleep 5

    # Configure apt sources correctly
    - name: Configure apt repositories
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
        mode: '0644'

    - name: Clean apt cache
      command: apt-get clean

    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: apt_update_result

    # Remove conflicting containerd package
    - name: Remove conflicting containerd package
      apt:
        name: containerd
        state: absent
      ignore_errors: yes

    # Add Docker’s official GPG key
    - name: Add Docker's official GPG key
      shell: | 
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Set up Docker stable repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        mode: '0644'

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE and other required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - python3-pip

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    # Add current user to docker group
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user | default('ubuntu') }}"
        groups: docker
        append: yes
